name: Build ROG3 Android 16 Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/YiYumagiccloud/android_kernel_asus_sm8250
          kernel-branch: lineage-23.0
          
          # 核心配置：基础 + 华硕补丁
          config: vendor/kona-perf_defconfig vendor/asus/obiwan.config
          arch: arm64
          
          # 编译器修复
          aosp-clang: true
          aosp-clang-version: r522815
          # 必须添加下面这一行，解决 "AOSP GCC is required" 错误
          aosp-gcc: true
          
          # 打包设置
          anykernel3: true
