name: Build ROG3 Android 16 Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/YiYumagiccloud/android_kernel_asus_sm8250
          kernel-branch: lineage-23.0
          
          # 依然使用这两个配置
          config: vendor/kona-perf_defconfig vendor/asus/obiwan.config
          arch: arm64
          
          # 1. 尝试使用这个更兼容的版本
          aosp-clang: true
          aosp-clang-version: r450784d
          
          # 2. 必须保留 GCC，否则会报你上次那个错
          aosp-gcc: true
          
          anykernel3: true
