# A simple action usage
name: Build Kernel
on:
  workflow_dispatch: # 允许手动触发

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须赋予写权限，否则无法发布 Release

    steps:
          - name: Build Kernel
            uses: dabao1955/kernel_build_action@main
            with:
              kernel-url: https://github.com/Rocky7842/android_kernel_asus_sm8250
              kernel-branch: lineage-23.0
              config: vendor/kona-perf_defconfig
              arch: arm64
              # 1. 必须同时开启，以满足脚本校验
              aosp-gcc: true
              aosp-clang: true
              # 2. 关键：将 Android 版本降回 12。
              # 只有这样，脚本才能在 Google 服务器上成功找到对应的 GCC 分支。
              android-version: 12
              # 3. 虽然 Android 环境是 12，但我们可以强制 Clang 使用新版本来适配安卓 16 内核

              # 4. 这里的参数非常关键，确保编译器行为正确
              extra-make-args: "LLVM=1 LLVM_IAS=1"
              disable-lto: true
              anykernel3: true
              release: true
