# A simple action usage
name: Build Kernel
on:
  workflow_dispatch: # 允许手动触发

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须赋予写权限，否则无法发布 Release

    steps:
          - name: Build Kernel
            uses: dabao1955/kernel_build_action@main
            with:
              # 1. 指向你提供的 Asus ROG 3 内核地址
              kernel-url: https://github.com/Rocky7842/android_kernel_asus_sm8250
              # 2. 分支必须匹配 lineage-23.0
              kernel-branch: lineage-23.0
              # 3. SM8250 (Kona) 的标准配置文件
              config: vendor/kona-perf_defconfig
              arch: arm64
              # 4. 现代内核通常强制使用 Clang
              aosp-gcc: false
              aosp-clang: true
              # 5. 建议使用这个更稳妥的版本
              android-version: 12
              aosp-clang-version: r450784d
              # 6. 其他功能开关
              disable-lto: true
              anykernel3: true
              # 7. 自动发布编译好的内核文件
              release: true
