name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    # 将运行环境锁定为 ubuntu-22.04
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Rocky7842/android_kernel_asus_sm8250
          kernel-branch: lineage-23.2
          config: vendor/kona-perf_defconfig
          arch: arm64
          
          # 针对较新的内核建议开启
          aosp-gcc: true
          aosp-clang: true
          
          # 如果编译 LineageOS 23.0 (Android 15/16)，
          # 建议尝试使用更现代的 Clang 版本以减少报错
          # clang-version: r510161 
          
          android-version: 12
          
          # LLVM=1 是 SM8250 内核的标配
          # 如果报错提示不支持 LLVM_IAS，可以尝试删掉 LLVM_IAS=1
          extra-make-args: "LLVM=1 LLVM_IAS=1"
          
          # 必须禁用 LTO 否则 GitHub Actions 的 7GB 内存会直接爆掉 (OOM)
          disable-lto: true
          
          anykernel3: true
          release: true
